name: guitar
description: "Guitarra - Leitor de partituras e tablaturas com suporte a Guitar Pro"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  file_picker: ^8.1.7
  intl: ^0.20.2
  xml: ^6.5.0
  uuid: ^4.5.1
  collection: ^1.19.1
  fl_chart: ^0.70.2
  permission_handler: ^11.3.1
  printing: ^5.14.2
  pdf: ^3.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/soundfonts/TimGM6mb.sf2
    - assets/Bravura.otf
    - assets/icon/icon.png

  fonts:
    - family: Bravura
      fonts:
        - asset: assets/Bravura.otf
